[workspace]
resolver = "3"
members = ["runtime", "crates/reussir-syntax", "crates/reussir-bytecode"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "(Apache-2.0 OR MIT)"

[workspace.dependencies]
ariadne = "0.5"
cstree = { version = "0.14", features = ["derive", "lasso_compat"] }
lasso = "0.7"
logos = "0.15"
palc = "0.0.2"
serde_json = { version = "1", features = ["arbitrary_precision"] }
stacker = "0.1.21"
stumpalo = "0.4.0"
rustc-hash = "2"

[profile.release]
lto = "thin"
