[package]
name = "reussir-backend-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Raw FFI bindings to the Reussir C API (libReussirCAPI) layered on the MLIR C API"
links = "ReussirCAPI"
build = "build.rs"

[lib]
name = "reussir_backend_sys"

[dependencies]
mlir-sys.workspace = true
