// RUN: %reussir-opt %s --reussir-token-instantiation="producers=false" \
// RUN:   --reussir-rc-dispatch-fusion \
// RUN:   --reussir-token-instantiation="acceptors=false" \
// RUN:   | %FileCheck %s --check-prefix=LATE
// RUN: %reussir-opt %s --reussir-token-instantiation \
// RUN:   --reussir-rc-dispatch-fusion \
// RUN:   | %FileCheck %s --check-prefix=EARLY
//
// A producer's token type is a function of the decrement's destructuring
// attributes, so the producer phase of token instantiation has to run after
// dispatch fusion has pinned the arm (the pipeline order). `V` has arms of
// 16 and 24 bytes (8-byte fused header + payload).
//
// LATE (pipeline order): the pinned decrements carry the arm's exact cell,
// so every later reuse of it is a static-size `token.ensure`.
// EARLY (producers instantiated first): fusion still pins the arm, but the
// result type it inherited is the dynamic `token<align : 8, size : ?>` --
// every reuse of that cell would go through the runtime realloc probe, even
// between equal sizes. This is the shape that cost nbe-hoas/nbe-closure
// ~10% of instructions before the phases were split.

module attributes {dlti.dl_spec = #dlti.dl_spec<!llvm.ptr<270> = dense<32> : vector<4xi64>, !llvm.ptr<271> = dense<32> : vector<4xi64>, !llvm.ptr<272> = dense<64> : vector<4xi64>, i8 = dense<[8, 32]> : vector<2xi64>, i16 = dense<[16, 32]> : vector<2xi64>, i64 = dense<64> : vector<2xi64>, i128 = dense<128> : vector<2xi64>, !llvm.ptr = dense<64> : vector<4xi64>, i1 = dense<8> : vector<2xi64>, i32 = dense<32> : vector<2xi64>, f16 = dense<16> : vector<2xi64>, f64 = dense<64> : vector<2xi64>, f128 = dense<128> : vector<2xi64>, "dlti.endianness" = "little", "dlti.mangling_mode" = "e", "dlti.legal_int_widths" = array<i32: 32, 64>, "dlti.stack_alignment" = 128 : i64, "dlti.function_pointer_alignment" = #dlti.function_pointer_alignment<32, function_dependent = true>, index = 64 : i64>, llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32", llvm.target_triple = "aarch64-unknown-linux-gnu"} {
  func.func @conv(%arg0: !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>) -> !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>> {
    %0 = reussir.rc.borrow(%arg0 : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>) : !reussir.ref<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}> shared>
    %1 = reussir.record.dispatch(%0 :!reussir.ref<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}> shared>) -> !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>{
      [0] -> {
      ^bb0(%arg1: !reussir.ref<!reussir.record<compound "_RNvC1V1A" [value] {i64}> shared>):
        %2 = reussir.ref.project(%arg1 : !reussir.ref<!reussir.record<compound "_RNvC1V1A" [value] {i64}> shared>) [0] : !reussir.ref<i64 shared>
        %3 = reussir.ref.load(%2 : !reussir.ref<i64 shared>) : i64
        // LATE: reussir.rc.dec{{.*}}: !reussir.nullable<!reussir.token<align : 8, size : 16>> {{.*}}boundMembers = array<i64>, destructureTag = 0 : index
        // EARLY: reussir.rc.dec{{.*}}: !reussir.nullable<!reussir.token<align : 8, size : ?>> {{.*}}destructureTag = 0 : index
        reussir.rc.dec(%arg0 : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>)
        %4 = reussir.record.compound(%3 : i64) : !reussir.record<compound "_RNvC1T1X" [value] {i64}>
        %5 = reussir.record.variant[0] (%4 : !reussir.record<compound "_RNvC1T1X" [value] {i64}>) : !reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>
        %6 = reussir.rc.create value(%5 : !reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>) : !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
        reussir.scf.yield %6 : !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
      }
      [1] -> {
      ^bb0(%arg1: !reussir.ref<!reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B">}>, !reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B">}>}> shared>):
        %2 = reussir.ref.project(%arg1 : !reussir.ref<!reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B">}>, !reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B">}>}> shared>) [0] : !reussir.ref<!reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>> shared>
        %3 = reussir.ref.load(%2 : !reussir.ref<!reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>> shared>) : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>
        %4 = reussir.ref.project(%arg1 : !reussir.ref<!reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B">}>, !reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B">}>}> shared>) [1] : !reussir.ref<!reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>> shared>
        %5 = reussir.ref.load(%4 : !reussir.ref<!reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>> shared>) : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>
        reussir.rc.inc(%3 : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>)
        reussir.rc.inc(%5 : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>)
        // LATE: reussir.rc.dec{{.*}}: !reussir.nullable<!reussir.token<align : 8, size : 24>> {{.*}}boundMembers = array<i64: 0, 1>, destructureTag = 1 : index
        // EARLY: reussir.rc.dec{{.*}}: !reussir.nullable<!reussir.token<align : 8, size : ?>> {{.*}}destructureTag = 1 : index
        reussir.rc.dec(%arg0 : !reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>)
        %6 = func.call @conv(%3) : (!reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>) -> !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
        %7 = func.call @conv(%5) : (!reussir.rc<!reussir.record<variant "_RC1V" {!reussir.record<compound "_RNvC1V1A" [value] {i64}>, !reussir.record<compound "_RNvC1V1B" [value] {!reussir.record<variant "_RC1V">, !reussir.record<variant "_RC1V">}>}>>) -> !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
        %8 = reussir.record.compound(%6, %7 : !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>, !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>) : !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y">}>, !reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y">}>}>
        %9 = reussir.record.variant[1] (%8 : !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y">}>, !reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y">}>}>) : !reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>
        %10 = reussir.rc.create value(%9 : !reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>) : !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
        reussir.scf.yield %10 : !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
      }
    }
    return %1 : !reussir.rc<!reussir.record<variant "_RC1T" {!reussir.record<compound "_RNvC1T1X" [value] {i64}>, !reussir.record<compound "_RNvC1T1Y" [value] {!reussir.record<variant "_RC1T">, !reussir.record<variant "_RC1T">}>}>>
  }
}
